apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dotnet-sample-app.fullname" . }}-secret
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
