# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sample-python-app
#   labels:
#     app: sample-python-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: sample-python-app
#   template:
#     metadata:
#       labels:
#         app: sample-python-app
#     spec:
#       containers:
#       - name: python-app
#         image: mojomughil/python-sample-app-demo:v1
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample-app
  labels:
    app: dotnet-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-sample-app
  template:
    metadata:
      labels:
        app: dotnet-sample-app
    spec:
      containers:
      - name: dotnet-app
        image: mojomughil/dotnet-sample-app-demo:v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: Database__ConnectionString
          value: "Docker_connection_to_DB"
        - name : InputEnvironmentName
          value: "Docker"
