apiVersion: v1
kind: Service
metadata:
  name: python-django-app-service
spec:
  type: NodePort
  selector:
    app: sample-python-app
  ports:
    - port: 8010
      targetPort: 80
      # Optional field
      nodePort: 30007
