apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet-sample-app.fullname" . }}-deployment
  labels:
    app: {{ include "dotnet-sample-app.fullname" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dotnet-sample-app.fullname" . }}-pods
  template:
    metadata:
      labels:
        app: {{ include "dotnet-sample-app.fullname" . }}-pods
    spec:
      containers:
        - name: dotnet-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "dotnet-sample-app.fullname" . }}-config
            - secretRef:
                name: {{ include "dotnet-sample-app.fullname" . }}-secret
